parameters:
    genj_short_url.entity.short_url.class: Genj\ShortUrlBundle\Entity\ShortUrl
    genj_short_url.entity.short_url_repository.class: Genj\ShortUrlBundle\Entity\ShortUrlRepository

services:
    genj_short_url.entity.short_url_repository:
        factory_service: doctrine
        factory_method: getRepository
        class: %genj_short_url.entity.short_url_repository.class%
        arguments: [%genj_short_url.entity.short_url.class%]

    genj_short_url.event_listener.request_listener:
        class: Genj\ShortUrlBundle\EventListener\RequestListener
        scope: request
        arguments:
            - @request
            - @doctrine.orm.entity_manager
            - @genj_short_url.entity.short_url_repository
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
